name: build_7zz_self_host
on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build_7zz_self_host.yml
      - build/7zz/*
      - Dockerfile

jobs:
  build_armel:
    runs-on: armel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        run: ${{ github.workspace }}/build/7zz/build.sh

      - name: List Dir
        run: ls -lRt ${{ github.workspace }}



